export default {
	CREATE_201: 'CREATE_201',
	CREATE_ERROR: 'CREATE_ERROR',
	CREATE_LOADING: 'CREATE_LOADING',

	DELETE_204: 'DELETE_204',
	DELETE_ERROR: 'DELETE_ERROR',
	DELETE_LOADING: 'DELETE_LOADING',

	FETCH_ALL_200: 'FETCH_ALL_200',
	FETCH_ALL_ERROR: 'FETCH_ALL_ERROR',
	FETCH_ALL_LOADING: 'FETCH_ALL_LOADING',

	SHOW_200: 'SHOW_200',
	SHOW_ERROR: 'SHOW_ERROR',
	SHOW_LOADING: 'SHOW_LOADING',

	UPDATE_200: 'UPDATE_200',
	UPDATE_ERROR: 'UPDATE_ERROR',
	UPDATE_LOADING: 'UPDATE_LOADING'
}
